import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProviders } from "@/components/SessionProvider";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Service",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SessionProviders>
          <Providers>{children}</Providers>
        </SessionProviders>
      </body>
    </html>
  );
}
